homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('myhooby/', views.myhooby, name='myhooby'),
    path('contact/', views.contact, name='contact'),
    path('resume/', views.resume, name='resume'),

    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def aboutme(request):
    return render(request, 'aboutme.html')

def myhooby(request):
    return render(request, 'myhobby.html')

def contact(request):
    return render(request, 'contact.html')

def resume(request):
    return render(request, 'resume.html')

homepage/templates/aboutme.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        {% include 'navbar.html' %}
        

        <div class="col-sm-12" style="height: 64em;background-color: #2A363B">
            <div class="row">
            <div class="col-sm-6">
            <h1 style="text-align: left;padding-top:2em;padding-left: 2em;color:#99B898">About Me</h1>
            <h4 id="hello">Hello there!</h4>
            <P id="aboutmepar">My name is Hanif and i was born at 11 March,2000 at sukabumi. When i was a child all do is go outside and just forget anything and just play around with other child. I grow up in a small family with elder sister. As i grow up i realize the world isn't always sunshine and rainbows, so i study like a lot to get good grades untill i get to go top school and university. Now, i am here trying to find what i like. I realize since i was middle school i am interesed in art espesially in design and visuals. I might persue that, and just go all out and double down for something that i like .</P>
           </div>

           <div class="col-sm-6">
            <img id="profilepic" src="https://sleepy-snorlax.herokuapp.com/pp.jpg">
           </div>
        </div>
        </div>
    </body>


<div class="footer" style="height: 17em; background-color:#2A363B">
        <div class="row">
        <div class="col-sm-6" style="height: 17.8em;background-color:#99B898">
    <ul class="list-unstyled">
      <li>
        <a id="link"href="{% url 'homepage:index' %}">Home</a>
      </li>
      <li>
        <a id="link"href="{% url 'homepage:aboutme' %}">About Me</a>
      </li>
      <li>
        <a id="link"href="{% url 'homepage:contact' %}">Contact</a>
      </li>
      <li>
          <a id="link"href="{% url 'homepage:resume' %}">Resume</a>
      </li>
    </ul>
  </div>
            
            
        <div class="col-sm-6" style="background-color:#99B898">
        <ul class="list-1">
        <li>
            <a id="button_a"href="#" class="btn btn-light btn-sm " role="button" aria-pressed="true"style="text-align: center">Send me an email</a>
        </li>
       <li>
    <div class="mb-5 flex-center" style="font-size: 24px;text-align: center; color: white;">

      <a class="fb-ic">
        <i class="fa fa-instagram"></i>
           </a>
      <!-- Twitter -->
      <a class="tw-ic">
        <i class="fa fa-twitter"></i>
      </a>
      <!-- Google +-->
      <a class="gplus-ic">
        <i class="fa fa-google-plus"> </i>
      </a>
      <!--Linkedin -->
      <a class="li-ic">
        <i class="fa fa-linkedin-in "> </i>
      </a>
      <!--Github-->
      <a class="ins-ic">
        <i class="fa fa-github-square"> </i>
      </a>

    </div>
  
    </ul>
            </div>    
        
        </div>
    </div>
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% include 'navbar.html' %}
        <div class="col-sm-12" style="height: 48em;background-color: #2A363B">
                <div class="row">
                <div class="col-sm-6">
                <h1 style="text-align: left;padding-top:2em;padding-left: 2em;color:#FF847C">Contact me</h1>
                <form>
                        <div class="form-group">
                                <label for="exampleFormControlInput1">Email address</label>
                                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                              </div>

                        <div class="form-group">
                                <label for="exampleFormControlTextarea1">Send Me an email</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="8"></textarea>
                              </div>
                        <button id="buttonsend"type="buttons" class="btn btn-secondary">Send a message</button>
                </form>
                </div>

                <div class="col-sm-6">
    
                </div>
            </div>

            <div class="footercontact" >
        <div class="row">
        <div class="col-sm-6" style="height: 17.8em;background-color:#FF847C">
    <ul class="list-unstyled">
      <li>
        <a id="link"href="{% url 'homepage:index' %}">Home</a>
      </li>
      <li>
        <a id="link"href="{% url 'homepage:aboutme' %}">About Me</a>
      </li>
      <li>
        <a id="link"href="{% url 'homepage:contact' %}">Contact</a>
      </li>
      <li>
          <a id="link"href="{% url 'homepage:resume' %}">Resume</a>
      </li>
    </ul>
  </div>
            
            
        <div class="col-sm-6" style="background-color:#FF847C">
        <ul class="list-1">
        <li>
            <a id="button_a"href="'mailto: heyitshanif@gmail.com'" class="btn btn-light btn-sm " role="button" aria-pressed="true"style="text-align: center">Send me an email</a>
        </li>
       <li>
    <div class="mb-5 flex-center" style="font-size: 48px;text-align: center; color: white;">

      <a class="fb-ic">
        <i class="fa fa-instagram"></i>
           </a>
      <!-- Twitter -->
      <a class="tw-ic">
        <i class="fa fa-twitter"></i>
      </a>
      <!-- Google +-->
      <a class="gplus-ic">
        <i class="fa fa-google-plus"> </i>
      </a>
      <!--Linkedin -->
      <a class="li-ic">
        <i class="fa fa-linkedin-in "> </i>
      </a>
      <!--Github-->
      <a class="ins-ic">
        <i class="fa fa-github-square"> </i>
      </a>

    </div>
  
    </ul>
            </div>    
        
        </div>
        </div>

</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
  
        <nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FF847C;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:aboutme' %}">About Me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact me</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:resume' %}">Resume</a>
      </li>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:myhooby' %}">My hobby</a>
  </li>
    </ul>
  </div>
</nav>


    <div class="col-sm-12" style="height: 42em;background-color: #2A363B">
    <h1 style="text-align: center;padding-top:6em;">Welcome to my website</h1>
        <h3 style="text-align:center">2nd year computer sciente studnet at University of Indonesia</h3>
    </div>
        
        
    <div class="section2">
      <div class="row">
        <div class="col-sm-6">
            <div class="card" style="width: 75%; height:87% ;">
      <img src="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">My Story</h5>
        <p class="card-text">Hello, my name is Muhammad Hanif, you can call me Hanif. I was born in small town that is called sukabumi. Since i was a child, i  enjoy painting and drawing . As i grow older and older i realize that i like creating things especially art that have visuals.</p>
          
      </div>
    </div>
        </div>
        <div class="col-sm-6">
        <div class="card" style="width: 75%;height: 87%;">
      <div class="card-body">
        <h5 class="card-title">What can i do </h5>
        <p class="card-text">To keep it very simple . I can do a bunch of thing that correlated visuals. I do well on photography and cinematography, still expanding my skills with painting and digital design </p>
      </div>
        <img src="https://images.unsplash.com/photo-1476763752342-d5cf7e5eb6cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" class="card-img-bottom">
    </div>

    </div>
      </div>
</div>
        
        <di class="footer" style="height: 17.8em; background-color:red">
            <div class="row">
            <div class="col-sm-6" style="height: 17.8em;background-color:#FECEA8">
        <ul class="list-unstyled">
          <li>
            <a id="link"href="#!">Home</a>
          </li>
          <li>
            <a id="link"href="aboutme.html">About Me</a>
          </li>
          <li>
            <a id="link"href="contact.html">Contact</a>
          </li>
          <li>
              <a id="link"href="resume.html">Resume</a>
          </li>
          <li>
              <a id="link"href="myhobby.html">My hobby</a>
          </li>
        </ul>
      </div>
                
                
            <div class="col-sm-6" style="background-color:#FECEA8">
            <ul class="list-1">
            <li>
                <a id="button_a"href="mailto: heyitshanif@gmail.com" class="btn btn-light btn-sm " role="button" aria-pressed="true"style="text-align: center">Send me an email</a>
            </li>
           <li>
        <div class="mb-5 flex-center" style="font-size: 24px;text-align: center; color: white;">

          <a class="fb-ic" href="instagram.com/hnfxz">
            <i class="fa fa-instagram"href="https://www.instagram.com/hnfxz/"></i>
               </a>
          <!-- Twitter -->
          <a class="tw-ic"href="www.twitter.com/heyitshanif">
            <i class="fa fa-twitter"href="www.twitter.com/heyitshanif"></i>
          </a>
          <!-- Google +-->
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fa fa-linkedin-in "> </i>
          </a>
          <!--Github-->
          <a class="ins-ic"href="https://gitlab.com/users/mhanif-82">
            <i class="fa fa-github-square" href="https://gitlab.com/users/mhanif-82"> </i>
          </a>

        </div>
      
        </ul>
                </div>    
            
            </div>
        </di>
    </body>
</html>

homepage/templates/myhobby.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    {% include 'navbar.html' %}
    <body style="background-color:#2A363B">
        <div class="container">

            <h1 class="font-weight-bold text-center text-lg-left mt-4 mb-0" style="color:#FECEA8">My hobby</h1>
          
            <hr class="mt-2 mb-5">
          
            <div class="row text-center text-lg-left">
          
              <div class="col-lg-6 col-md-6 ">
                <a href="#" class="d-block mb-4 h-100">
                      <img class="img-fluid img-thumbnail" src="https://images.unsplash.com/photo-1456086272160-b28b0645b729?ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80" alt="">
                    </a>
              </div>
              <div class="col-lg-6 col-md-6 ">
                <a href="#" class="d-block mb-4 h-100">
                      <img class="img-fluid img-thumbnail" src="https://images.unsplash.com/uploads/141148589884100082977/a816dbd7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                    </a>
              </div>
              <div class="col-lg-6 col-md-6 ">
                <a href="#" class="d-block mb-4 h-100">
                      <img class="img-fluid img-thumbnail" src="https://images.unsplash.com/photo-1523043829291-4195e5c69656?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                    </a>
              </div>
              <div class="col-lg-6 col-md-6 ">
                <a href="#" class="d-block mb-4 h-100">
                      <img class="img-fluid img-thumbnail" src="https://images.unsplash.com/photo-1542751371-adc38448a05e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                    </a>
              </div>
            </div>
          
          </div>
          <!-- /.container -->
    </body>
</html>

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light"style="background-color: #FF847C;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:aboutme' %}">About Me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact me</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:resume' %}">Resume</a>
      </li>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'homepage:myhooby' %}">My hobby</a>
  </li>
    </ul>
  </div>
</nav>

homepage/templates/resume.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        </head>
        <body>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
{% include 'navbar.html' %}
    <body style="background-color:#2A363B">
        <header>
            <img src="{% static 'images/Untitled.png' %}" class="center">
        </header>
    </body>
</html>